app = "simon-website"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[http_service]
  internal_port = 8043
  force_https = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
